### ISSUE TITLE
Uncaught AttributeError in charm code: 'str' object has no attribute 'items'

### ISSUE THREAD

**Issue by ggouzi** [VariableDeclared/charm-cis-harden#1]
juju run output
```
juju run --wait 10m cis-hardening-ceph-fs/2 -- execute-cis
...
USG will execute the following command for generating fix: oscap xccdf generate --profile xccdf_org.ssgproject.content_profile_cis_level2_server_customized fix --fix-type bash --tailoring-file /tmp/tmpg9ck_uwl  /usr/share/ubuntu-scap-security-guides/current/benchmarks/ssg-ubuntu2204-xccdf.xml > /var/lib/usg/xccdf_org.ssgproject.content_profile_cis_level2_server_customized-20241014.0715.sh
USG generate-fix command completed.
USG will execute the following command for remediating: bash -x /var/lib/usg/xccdf_org.ssgproject.content_profile_cis_level2_server_customized-20241014.0715.sh 2>&1 1>remediation-20241014.0715.log | tee -a remediation-20241014.0715.log
USG fix command completed.
A system reboot is required to complete the fix process.
Please run usg audit after reboot.
Uncaught AttributeError in charm code: 'str' object has no attribute 'items'
Use `juju debug-log` to see the full traceback.
ERROR the following task failed:
 - id "226" with return code 1

use 'juju show-task' to inspect the failure
```

juju debug-log output
```
unit-grafana-agent-container-0: 07:18:33 INFO juju.worker.uniter.operation ran "update-status" hook (via hook dispatching script: dispatch)
unit-cis-hardening-ceph-fs-2: 07:18:32 WARNING unit.cis-hardening-ceph-fs/2.execute-cis USG fix command completed.
unit-cis-hardening-ceph-fs-2: 07:18:32 WARNING unit.cis-hardening-ceph-fs/2.execute-cis A system reboot is required to complete the fix process.
unit-cis-hardening-ceph-fs-2: 07:18:32 WARNING unit.cis-hardening-ceph-fs/2.execute-cis Please run usg audit after reboot.
unit-cis-hardening-ceph-fs-2: 07:18:32 ERROR unit.cis-hardening-ceph-fs/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-cis-hardening-ceph-fs-2/charm/./src/charm.py", line 56, in <module>
    ops.main(CharmCisHardeningCharm)  # type: ignore
  File "/var/lib/juju/agents/unit-cis-hardening-ceph-fs-2/charm/venv/ops/__init__.py", line 343, in __call__
    return _main.main(charm_class=charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-cis-hardening-ceph-fs-2/charm/venv/ops/_main.py", line 543, in main
    manager.run()
  File "/var/lib/juju/agents/unit-cis-hardening-ceph-fs-2/charm/venv/ops/_main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-cis-hardening-ceph-fs-2/charm/venv/ops/_main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-cis-hardening-ceph-fs-2/charm/venv/ops/_main.py", line 134, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-cis-hardening-ceph-fs-2/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-cis-hardening-ceph-fs-2/charm/venv/ops/framework.py", line 857, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-cis-hardening-ceph-fs-2/charm/venv/ops/framework.py", line 947, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-cis-hardening-ceph-fs-2/charm/./src/charm.py", line 51, in _cis_harden_action
    event.set_results("Complete!")
  File "/var/lib/juju/agents/unit-cis-hardening-ceph-fs-2/charm/venv/ops/charm.py", line 211, in set_results
    self.framework.model._backend.action_set(results)
  File "/var/lib/juju/agents/unit-cis-hardening-ceph-fs-2/charm/venv/ops/model.py", line 3571, in action_set
    flat_results = _format_action_result_dict(results)
  File "/var/lib/juju/agents/unit-cis-hardening-ceph-fs-2/charm/venv/ops/model.py", line 3231, in _format_action_result_dict
    for key, value in input.items():
AttributeError: 'str' object has no attribute 'items'
```

Issues comes from `event.set_results` which accepts a dict instead of a string

**Comment by VariableDeclared** [comment]
Thanks @ggouzi will be fixed in next iteration!

**Comment by VariableDeclared** [comment]
Addressed in https://github.com/VariableDeclared/charm-cis-harden/commit/d082df02d09a5ad08ffda65626f146a57f7675db feel free to test again @ggouzi
